//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: EnumList.proto
namespace EnumList
{
    [global::ProtoBuf.ProtoContract(Name=@"NetMessageCmd")]
    public enum NetMessageCmd
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"LOGIN", Value=1)]
      LOGIN = 1,
            
      [global::ProtoBuf.ProtoEnum(Name=@"MONEY", Value=2)]
      MONEY = 2
    }
  
}